name: timeline_tile
description: A package to help you build highly customisable timelines with Flutter.
version: 3.0.0
repository: https://github.com/JHBitencourt/timeline_tile
homepage: https://github.com/JHBitencourt/timeline_tile
issue_tracker: https://github.com/JHBitencourt/timeline_tile/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
